### ISSUE TITLE
form: make RJSF id separator to be customizable for each form

### ISSUE THREAD

**Issue by pamfilos** [cern-sis/react-formule#61]
Righ now we have `$` character as the separator for the construction of ids for individual fields.
e.g. https://github.com/cern-sis/react-formule/blob/master/src/forms/templates/utils/index.js#L1

This can be an issue and be erroneous, for forms that need to use field names that might include this character 
(e.g field with name `$schema` )

- [ ] we should be able to customize this behavior
- [ ] it should be customizable by `Form` and NOT by `FormuleContext`

**Comment by miguelgrc** [comment]
Added as part of #64
