### ISSUE TITLE
Issue while setting up demo

### ISSUE THREAD

**Issue by Ansh-Sarkar** [cern-sis/react-formule#89]
## Problem Being Faced
Hi ! I was trying to setup the formule demo. Followed all the steps in the `README.md`
- [x] Cloned the repo locally and switched to the `formule-demo` folder
- [x] Ran the `yarn install` command. Packages were installed without any issues.
- [ ] However, now that I run `yarn dev` it shows me a bunch of errors saying that certain components and modules are missing.

![image](https://github.com/user-attachments/assets/f108a281-90e0-479c-8068-3336a3f714d3)
![image](https://github.com/user-attachments/assets/ca453a20-745a-47c5-b88e-9593b59b7a85)

## Expected Behaviour
The expected behaviour is to be able to have a functioning local demo of formule for development purposes.

**Comment by miguelgrc** [comment]
Hi, have you also run `yarn install` in react-formule first?

**Comment by Ansh-Sarkar** [comment]
Oh ok. My bad. So we need to run the `yarn install` command in the root directory first and then cd into the demo project folder and run `yarn dev`. It's working now. Thanks a ton !

Do you think that updating the `README.md` is required ? It just felt slightly confusing since the root `README` refers to running the `formule-demo`.

**Comment by miguelgrc** [comment]
Yes, `yarn install` in the root first and then `yarn install` and `yarn dev` in the demo.
You're right in that the [README](https://github.com/cern-sis/react-formule/blob/master/formule-demo/README.md) could be a bit more clear, I will update it.

**Comment by Ansh-Sarkar** [comment]
Sure thing. Thanks.
